# Generated by Django 5.0 on 2024-02-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderitem_order_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
